global:
  resolve_timeout: 5m
  smtp_smarthost: 'email-smtp.us-east-1.amazonaws.com:587'
  smtp_from: 'arismita@umd.edu'
  smtp_auth_username: ''
  smtp_auth_password: ''
  smtp_require_tls: true


receivers:
  - name: 'email-me'
    email_configs:
      - to: 'arismita@umd.edu'
        send_resolved: true


route:
  receiver: 'email-me'
  group_by: ['alertname']
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 1h