name: CI - Build and Push Docker Image

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Install Docker Compose
      run: |
        sudo curl -L "https://github.com/docker/compose/releases/download/v2.24.5/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
        sudo chmod +x /usr/local/bin/docker-compose
        docker-compose version

    - name: Login to DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Override image names in docker-compose
      run: |
        sed -i "s|ghcr.io/open-telemetry|${{ secrets.DOCKER_USERNAME }}|g" docker-compose.yml

    - name: Set DockerHub username env var
      run: echo "DOCKER_USERNAME=${{ secrets.DOCKER_USERNAME }}" >> $GITHUB_ENV

    - name: Dynamically Build & Push Only Changed Services
      run: |
        echo "📂 Detecting services from src/ directory..."
        cd src
        services=($(find . -maxdepth 1 -mindepth 1 -type d -exec basename {} \;))
        cd ..

        for service in "${services[@]}"; do
          if git diff --quiet origin/main HEAD -- ./src/$service; then
            echo "🟡 No changes in $service — skipping"
          else
            echo "🟢 Changes detected in $service — building and pushing..."
            docker build -t $DOCKER_USERNAME/$service:latest ./src/$service
            docker push $DOCKER_USERNAME/$service:latest
          fi
        done
      env:
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}